
/**************************************************************
 *	
 *	EHURT, 8 bit, 11025Hz,
 *	1 channel, 6480 bytes/channel
 *	Total Size: 1 * 6480 + 4 (header) = 6524 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonia\Downloads\AntoniaDeliyianni_FinalProject\EHURT.aiff
 *	Time-stamp: Tue Apr 12 18:41:18 2016
 *	
 **************************************************************/

#ifndef __EHURTH__
#define __EHURTH__

#define EHURTFREQ 11025
#define EHURTLEN 6480

extern const unsigned char EHURT[6480];

#endif /* __EHURTH__ */
