
/**************************************************************
 *	
 *	EPUNCH, 8 bit, 11025Hz,
 *	1 channel, 8376 bytes/channel
 *	Total Size: 1 * 8376 + 4 (header) = 8420 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonia\Downloads\AntoniaDeliyianni_FinalProject\EPUNCH.aiff
 *	Time-stamp: Tue Apr 12 18:41:39 2016
 *	
 **************************************************************/

#ifndef __EPUNCHH__
#define __EPUNCHH__

#define EPUNCHFREQ 11025
#define EPUNCHLEN 8376

extern const unsigned char EPUNCH[8376];

#endif /* __EPUNCHH__ */
