
/**************************************************************
 *	
 *	EPUNCH2, 8 bit, 22050Hz,
 *	1 channel, 10704 bytes/channel
 *	Total Size: 1 * 10704 + 4 (header) = 10748 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonia\Downloads\AntoniaDeliyianni_FinalProject\EPUNCH2.aiff
 *	Time-stamp: Tue Apr 12 18:43:11 2016
 *	
 **************************************************************/

#ifndef __EPUNCH2H__
#define __EPUNCH2H__

#define EPUNCH2FREQ 22050
#define EPUNCH2LEN 10704

extern const unsigned char EPUNCH2[10704];

#endif /* __EPUNCH2H__ */
