
/**************************************************************
 *	
 *	Game_Over, 8 bit, 11025Hz,
 *	1 channel, 138350 bytes/channel
 *	Total Size: 1 * 138350 + 4 (header) = 138394 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonia\Downloads\AntoniaDeliyianni_FinalProject\Game_Over.aiff
 *	Time-stamp: Wed Apr 20 11:06:55 2016
 *	
 **************************************************************/

#ifndef __GAME_OVERH__
#define __GAME_OVERH__

#define GAME_OVERFREQ 11025
#define GAME_OVERLEN 138350

extern const unsigned char Game_Over[138350];

#endif /* __GAME_OVERH__ */
