
/**************************************************************
 *	
 *	HURT, 8 bit, 22050Hz,
 *	1 channel, 11176 bytes/channel
 *	Total Size: 1 * 11176 + 4 (header) = 11220 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonia\Downloads\AntoniaDeliyianni_FinalProject\HURT.aiff
 *	Time-stamp: Mon Apr 11 10:04:04 2016
 *	
 **************************************************************/

#ifndef __HURTH__
#define __HURTH__

#define HURTFREQ 22050
#define HURTLEN 11176

extern const unsigned char HURT[11176];

#endif /* __HURTH__ */
