
/**************************************************************
 *	
 *	PUNCH, 8 bit, 22050Hz,
 *	1 channel, 12120 bytes/channel
 *	Total Size: 1 * 12120 + 4 (header) = 12164 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonia\Downloads\AntoniaDeliyianni_FinalProject\PUNCH.aiff
 *	Time-stamp: Mon Apr 11 10:03:52 2016
 *	
 **************************************************************/

#ifndef __PUNCHH__
#define __PUNCHH__

#define PUNCHFREQ 22050
#define PUNCHLEN 12120

extern const unsigned char PUNCH[12120];

#endif /* __PUNCHH__ */
