
/**************************************************************
 *	
 *	PUNCH2, 8 bit, 11025Hz,
 *	1 channel, 4136 bytes/channel
 *	Total Size: 1 * 4136 + 4 (header) = 4180 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonia\Downloads\AntoniaDeliyianni_FinalProject\PUNCH2.aiff
 *	Time-stamp: Mon Apr 11 10:03:46 2016
 *	
 **************************************************************/

#ifndef __PUNCH2H__
#define __PUNCH2H__

#define PUNCH2FREQ 11025
#define PUNCH2LEN 4136

extern const unsigned char PUNCH2[4136];

#endif /* __PUNCH2H__ */
