
/**************************************************************
 *	
 *	SailorMoon, 8 bit, 11025Hz,
 *	1 channel, 225309 bytes/channel
 *	Total Size: 1 * 225309 + 4 (header) = 225353 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonia\Downloads\AntoniaDeliyianni_FinalProject\SailorMoon.aiff
 *	Time-stamp: Fri Apr 15 16:28:08 2016
 *	
 **************************************************************/

#ifndef __SAILORMOONH__
#define __SAILORMOONH__

#define SAILORMOONFREQ 11025
#define SAILORMOONLEN 225309

extern const unsigned char SailorMoon[225309];

#endif /* __SAILORMOONH__ */
