
/**************************************************************
 *	
 *	Stage_12, 8 bit, 11025Hz,
 *	1 channel, 1412096 bytes/channel
 *	Total Size: 1 * 1412096 + 4 (header) = 1412140 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonia\Downloads\AntoniaDeliyianni_FinalProject\Stage_12.aiff
 *	Time-stamp: Fri Apr 15 10:04:38 2016
 *	
 **************************************************************/

#ifndef __STAGE_12H__
#define __STAGE_12H__

#define STAGE_12FREQ 11025
#define STAGE_12LEN 1412096

extern const unsigned char Stage_12[1412096];

#endif /* __STAGE_12H__ */
