
/**************************************************************
 *	
 *	Stage_3, 8 bit, 11025Hz,
 *	1 channel, 1294336 bytes/channel
 *	Total Size: 1 * 1294336 + 4 (header) = 1294380 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonia\Downloads\AntoniaDeliyianni_FinalProject\Stage_3.aiff
 *	Time-stamp: Fri Apr 15 16:31:51 2016
 *	
 **************************************************************/

#ifndef __STAGE_3H__
#define __STAGE_3H__

#define STAGE_3FREQ 11025
#define STAGE_3LEN 1294336

extern const unsigned char Stage_3[1294336];

#endif /* __STAGE_3H__ */
