
/**************************************************************
 *	
 *	Tuxedo, 8 bit, 11025Hz,
 *	1 channel, 172995 bytes/channel
 *	Total Size: 1 * 172995 + 4 (header) = 173039 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonia\Downloads\AntoniaDeliyianni_FinalProject\Tuxedo.aiff
 *	Time-stamp: Fri Apr 15 10:16:36 2016
 *	
 **************************************************************/

#ifndef __TUXEDOH__
#define __TUXEDOH__

#define TUXEDOFREQ 11025
#define TUXEDOLEN 172995

extern const unsigned char Tuxedo[172995];

#endif /* __TUXEDOH__ */
