
/**************************************************************
 *	
 *	Victory, 8 bit, 11025Hz,
 *	1 channel, 50095 bytes/channel
 *	Total Size: 1 * 50095 + 4 (header) = 50139 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Antonia\Downloads\AntoniaDeliyianni_FinalProject\Victory.aiff
 *	Time-stamp: Tue Apr 19 06:30:25 2016
 *	
 **************************************************************/

#ifndef __VICTORYH__
#define __VICTORYH__

#define VICTORYFREQ 11025
#define VICTORYLEN 50095

extern const unsigned char Victory[50095];

#endif /* __VICTORYH__ */
